name: The Captain ~ The Pilot ~ The Driver
favicon: null
layout_spectrum: 0.5522091924212873
typography_spectrum: 0.5890464710537344
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#71A7FE'
    - '#399AE7'
    - '#3B407C'
    - '#547AB1'
    - '#CEAFC0'
  brandStrength: 0.5911497639026493
  lightness: 0.07910778280347586
  saturation: 0.5876905363984406
  rhythmicContrast: 0.6439131051301956
purpose: []
